{-# LANGUAGE PatternSynonyms #-}

module FreeType.Control.Parameter where

import           FreeType.Core.Types

#include "ft2build.h"
#include FT_FREETYPE_H

#include "freetype/ftparams.h"

pattern FT_PARAM_TAG_IGNORE_TYPOGRAPHIC_FAMILY
      , FT_PARAM_TAG_IGNORE_PREFERRED_FAMILY
      , FT_PARAM_TAG_IGNORE_TYPOGRAPHIC_SUBFAMILY
      , FT_PARAM_TAG_IGNORE_PREFERRED_SUBFAMILY
      , FT_PARAM_TAG_INCREMENTAL
      , FT_PARAM_TAG_LCD_FILTER_WEIGHTS
      , FT_PARAM_TAG_RANDOM_SEED
      , FT_PARAM_TAG_STEM_DARKENING
      , FT_PARAM_TAG_UNPATENTED_HINTING
     :: FT_UInt
pattern FT_PARAM_TAG_IGNORE_TYPOGRAPHIC_FAMILY    = #const FT_PARAM_TAG_IGNORE_TYPOGRAPHIC_FAMILY
pattern FT_PARAM_TAG_IGNORE_PREFERRED_FAMILY      = #const FT_PARAM_TAG_IGNORE_PREFERRED_FAMILY
pattern FT_PARAM_TAG_IGNORE_TYPOGRAPHIC_SUBFAMILY = #const FT_PARAM_TAG_IGNORE_TYPOGRAPHIC_SUBFAMILY
pattern FT_PARAM_TAG_IGNORE_PREFERRED_SUBFAMILY   = #const FT_PARAM_TAG_IGNORE_PREFERRED_SUBFAMILY
pattern FT_PARAM_TAG_INCREMENTAL                  = #const FT_PARAM_TAG_INCREMENTAL
pattern FT_PARAM_TAG_LCD_FILTER_WEIGHTS           = #const FT_PARAM_TAG_LCD_FILTER_WEIGHTS
pattern FT_PARAM_TAG_RANDOM_SEED                  = #const FT_PARAM_TAG_RANDOM_SEED
pattern FT_PARAM_TAG_STEM_DARKENING               = #const FT_PARAM_TAG_STEM_DARKENING
pattern FT_PARAM_TAG_UNPATENTED_HINTING           = #const FT_PARAM_TAG_UNPATENTED_HINTING
